root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./tmp/web"
cmd = "npm run build:src && npm run build:css && templ generate && go build -o ./tmp/web ./cmd/web"
delay = 1000
exclude_dir = [
    "tmp",
    "vendor",
    "testdata",
    "node_modules",
    ".vscode",
    ".devcontainer",
    "internal/adapters/primary/web/dist",
]
exclude_file = [
    "tailwind.config.js",
    "package.json",
    "package-lock.json",
    ".node-version",
    ".gitignore",
]
exclude_regex = ["_test.go", "_templ.go", ".sql"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "templ", "js", "css"]
include_file = []
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = []
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
