version: "3.9"
services:
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: "financo"
      POSTGRES_PASSWORD: "local_dev"
      POSTGRES_DB: "financo_dev"
    ports:
      - "5432:5432"