name: "go-financo"

services:
  migrate:
    image: migrate/migrate
    volumes:
      - ./cmd/db/migrations:/migrations

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  db:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: "financo"
      POSTGRES_PASSWORD: "local_dev"
      POSTGRES_DB: "financo_dev"
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  redis-data: