version: '3'
services:
  redis:
    image: redis:7.2
    ports:
      - 6379:6379

  postgres:
    image: postgres:16.1
    restart: always
    environment:
      POSTGRES_USER: fnncr
      POSTGRES_PASSWORD: local_dev
      POSTGRES_DB: fnncr_dev
    ports:
      - 5432:5432